list_labs = {\
'CRAL' : ['CRAL', 'UMR 5574', 'UMR5574', 'UMR CNRS 5574', 'CNRS UMR 5574', 'CNRS UMR5574', 'CTR RECH ASTROPHYS LYON', 'CTR RECH ASTRON LYON', 'Centre de Recherche Astrophysique de Lyon'],\
'CRMN' : ['CRMN', 'FRE 3008', 'FRE3008', 'CNRS FRE 3008', 'FRE CNRS 3008', 'CTR RMN TRES HAUTS CHAMPS', 'CTR RMN TRES HAUTS CHAMPS FRE 3008'],\
'IGFL' : ['IGFL', 'UMR 5242', 'UMR5242', 'CNRS UMR 5242', 'UMR CNRS 5242', 'CNRS UMR5242', 'INST GENOM FONCT LYON', 'INST GENOM FONCTIONNELLE LYON', 'INST GENOM FONCT', 'INST GENOM FONCTIONNELLE'],\
'Lab Biol Mol Cell' : ['LBMC', 'UMR 5239', 'UMR5239', 'CNRS UMR 5239', 'CNRS UMR5239', 'UMR CNRS 5239', 'LAB BIOL MOL CELLULE', 'UMR 5665', 'UMR5665', 'CNRS UMR 5665', 'LAB BIOL MOL & CELLULAIRE', 'BIOL CELLULAIRE & MOL LAB', 'BIOL MOLEC & CELLULAIRE LAB'],\
'CHIM LAB' : ['CHIM LAB', 'LAB CHIM', 'UMR 5182', 'UMR5182', 'UMR CNRS 5182', 'CNRS UMR 5182', 'CNRS UMR5182'],\
'LIP' : ['LIP', 'UMR 5668', 'UMR5668', 'UMR CNRS 5668', 'CNRS UMR 5668', 'CNRS UMR5668', 'LAB LIP', 'LIP LAB', 'LAB INFORMAT PARALLELISME', 'INFORMAT PARALLELISME LAB', 'LAB INFORMAT & PARALLELISME', 'LAB INFORMAT PARALLEL'],\
'PHYS LAB' : ['PHYS LAB', 'UMR 5672', 'UMR5672', 'CNRS UMR 5672', 'UMR CNRS 5672', 'CNRS UMR5672', 'LAB PHYS'],\
'Lab Reprod & Dev Plantes' : ['RDP', 'UMR 5667', 'UMR5667', 'CNRS UMR 5667', 'CNRS UMR5667', 'UMR CNRS 5667', 'LAB REPROD & DEV PLANTES', 'REPROD & DEV PLANTES UMR5667'],\
'GEOL LAB' : ['GEOL LAB', 'LAB GEOL', 'UMR 5276', 'UMR5276', 'UMR CNRS 5276', 'CNRS UMR 5276', 'CNRS UMR5276', 'UMR LAB GEOL LYON 5276', 'LAB GEOL LYON'],\
'Lab Joliot Curie' : ['LJC', 'USR 3010', 'USR3010', 'USR CNRS 3010', 'CNRS USR3010', 'CNRS USR 3010', 'LAB JOLIOT CURIE', 'LAB TRANSDISCIPLINAIRE JOLIOT CURIE', 'LAB RECH JOLIOT CURIE', 'USR3010 LAB JOLIOT CURIE', 'LAB JOLIOT CURIE USR3010'],\
'UMPA' : ['UMPA', 'UNITE MATH PURES & APPL', 'UNITE MATH PURES & APPLIQUEES', 'UNIT MATH PURES & APPL', 'UMR 5669', 'UMR5669', 'UMR CNRS 5669', 'CNRS UMR 5669', 'CNRS UMR5669'],\
'VIRO' : ['VIRO', 'UNITE VIROL HUMAINE', 'LABORETRO', 'UNITE VIROL HUMAINE INSERM U758', 'U758', 'INSERM 758', 'INSERM U758'],\
'LAB SCI TERRE' : ['LAB SCI TERRE', 'UMR 5570', 'UMR5570', 'CNRS UMR 5570'],\
}

other_institutions = {\
'ENS Lyon' : ['Ecole Normale Super Lyon', 'ENS LYON', 'ENSL'],\
'ENS' : ['ENS', 'Ecole Normale Super'],\
'Hosp Civils Lyon' : ['Hosp Civils Lyon', 'HCL'],\
'UNIV LYON 1' : ['UNIV LYON 1', 'UCBL', 'UCB LYON', 'UCB LYON 1', 'UNIV CLAUDE BERNARD LYON 1', ],\
'INSA' : ['INSA', 'INST NATL SCI APPL'],\
'INRA' : ['INRA', 'INST NATL RECH AGRON'],\
'IXXI' : ['IXXI', 'INST SYST COMPLEXES RHONE ALPES IXXI', 'IXXI COMPLEX SYST INST', 'INST RHONE ALPIN SYST COMPLEXES IXXI', 'INST RHONE ALPIN SYST COMPLEXES'],\
'ECOLE CENT LYON' : ['ECOLE CENT LYON', 'ECL']
}

